# Generated by Django 3.2 on 2021-04-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('applink', models.CharField(max_length=200)),
                ('app_category', models.CharField(choices=[('Official', 'Official'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top secret', 'Top secret')], default=('Official', 'Official'), max_length=15)),
                ('sub_category', models.CharField(choices=[('Official', 'Official'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top secret', 'Top secret')], default=('Official', 'Official'), max_length=15)),
                ('points', models.IntegerField(default=0)),
                ('img', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('task_completed', models.BooleanField(default=False)),
                ('apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
