# Generated by Django 3.2 on 2021-04-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='apps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='android.app'),
        ),
    ]
